# Generated by Django 5.0.2 on 2024-02-09 10:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calory_counter_app', '0004_exercise_useractivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CounterModel',
            new_name='UserDetails',
        ),
    ]
