# Generated by Django 5.0.2 on 2024-02-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calory_counter_app', '0005_rename_countermodel_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('breakfast', 'Breakfast'), ('morning_snack', 'Morning Snack'), ('lunch', 'Lunch'), ('evening_snack', 'Evening Snack'), ('dinner', 'dinner')], max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=30)),
                ('calory', models.IntegerField()),
            ],
        ),
    ]
