# Generated by Django 5.0.2 on 2024-02-10 06:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calory_counter_app', '0007_alter_foodlist_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('foodlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calory_counter_app.foodlist')),
            ],
        ),
    ]
