# Generated by Django 5.0.2 on 2024-02-10 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calory_counter_app', '0008_dailyeating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodlist',
            old_name='name',
            new_name='food_name',
        ),
    ]
